alpine-gnu: openmpi 3.0.1
Since with 2.5.1:

In file included from src/common/pmix_jobdata.c:12:
/openmpi/openmpi-2.1.5/opal/mca/pmix/pmix112/pmix/include/pmix_server.h:383:55: error: unknown type name 'uid_t'; did you mean 'id_t'?

See also:
https://github.com/open-mpi/ompi/issues/1838